var APN = [
	{
		name: "FinFET_SiGe_EnsembleMC_3nm",
		title: "Three-Dimensional Analysis of 3 nm SiGe FinFETs by Ensemble Monte Carlo",
		creator: "luca",
		owner: "luca",
		archive: "Applications_Library/AdvancedTransport",
		appArea: "Advanced Transport",
		dim: "3d",
		tools: "sprocess snmesh garandmc",
		solvNetId: "applib",
		firstRelease: "T-2022.03",
		pdf: "greadme.pdf"
	},
	{
		name: "NSFET_SdeviceSBTE_3nm",
		title: "Coupled Sentaurus Device-Sentaurus Device QTX Simulations of 3 nm Silicon Three-Stack Nanoslab FETs",
		creator: "luca",
		owner: "luca",
		archive: "Applications_Library/AdvancedTransport",
		appArea: "Advanced Transport",
		dim: "3d",
		tools: "sprocess sdevice sdevice-qtx",
		solvNetId: "applib",
		firstRelease: "T-2022.03",
		pdf: "greadme.pdf"
	},
	{
		name: "Nanowire_Si_QTX_NEGF_5nm",
		title: "Non-Equilibrium Green's Function Simulation of Silicon 5 nm Node Nanowire FETs",
		creator: "luca",
		owner: "luca",
		archive: "Applications_Library/AdvancedTransport",
		appArea: "Advanced Transport",
		dim: "3d",
		tools: "sprocess sdevice qtx",
		solvNetId: "applib",
		firstRelease: "T-2022.03",
		pdf: "greadme.pdf"
	},
	{
		name: "Nanowire_Si_QTX_SBTE_5nm",
		title: "Three-Dimensional Simulation of Silicon 5 nm Node Nanowires Using the Subband Boltzmann Transport Equation",
		creator: "munkangc",
		owner: "munkangc",
		archive: "Applications_Library/AdvancedTransport",
		appArea: "Advanced Transport",
		dim: "3d",
		tools: "sprocess sbte",
		solvNetId: "applib",
		firstRelease: "M-2016.12 09/17/16",
		pdf: "greadme.pdf"
	},
	{
		name: "Resistance_InAs_Mo_DFT_NEGF",
		title: "Contact Resistance of Metal-InAs Interface from Ab Initio DFT NEGF Simulations",
		creator: "luca",
		owner: "luca",
		archive: "Applications_Library/AdvancedTransport",
		appArea: "Advanced Transport",
		dim: "2d",
		tools: "quantumatk",
		solvNetId: "applib",
		firstRelease: "T-2022.03",
		pdf: "greadme.pdf"
	},
	{
		name: "BCD",
		title: "Three-dimensional Simulation of Bipolar-CMOS-DMOS Devices",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/Analog",
		appArea: "Analog",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "E-2010.12 04/14/11",
		pdf: "greadme.pdf"
	},
	{
		name: "BCD_LayoutEditor_SWB",
		title: "Use Cases for Layout-Driven TCAD Simulations With Silicon Workbench-TCAD Sentaurus Interface",
		creator: "sayed",
		owner: "sayed",
		archive: "Applications_Library/Analog",
		appArea: "Analog",
		dim: "3d",
		tools: "siwb sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "U-2022.12",
		pdf: "greadme.pdf"
	},
	{
		name: "CopperPillar_FlipChip_Crack",
		title: "Flip-Chip Package Reliability Optimization With Copper Pillar Stress and Crack Modeling",
		creator: "karthikg",
		owner: "karthikg",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sintercon",
		solvNetId: "applib",
		firstRelease: "I-2013.12 02/28/14",
		pdf: "greadme.pdf"
	},
	{
		name: "CopperPillar_Reliability",
		title: "Reliability and Optimization of Copper Pillar Bumps in High-Performance Flip-Chip Packages",
		creator: "karthikg",
		owner: "karthikg",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Rely",
		dim: "3d",
		tools: "sintercon",
		keywords: "Copper Pillar Bumps Flip-Chip Packages",
		solvNetId: "applib",
		firstRelease: "I-2013.12 08/27/14",
		pdf: "greadme.pdf"
	},
	{
		name: "PackageAssembly_Stress",
		title: "Modeling Mechanical Stress Evolution During BEOL Fabrication and Package Assembly Process",
		creator: "adityap",
		owner: "adityap",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sintercon",
		keywords: "Stress Evolution BEOL Package Assembly",
		solvNetId: "applib",
		firstRelease: "I-2013.12 08/28/14",
		pdf: "greadme.pdf"
	},
	{
name: "Package_ThermomechanicalReliability",
title: "Coupled Thermomechanical Reliability Analysis of Power Semiconductor Packages",
tag: "new",
creator: "adityap",
owner: "adityap",
archive: "Applications_Library/Backend",
appArea: "Backend-Stress",
dim: "3d",
tools: "sinterconnect",
solvNetId: "applib",
firstRelease: "K-2015.06 09/01/15",
lastUpdate: "09/01/15",
pdf: "greadme.pdf"
	},
	{
		name: "SRAM_Backend",
		title: "Processing and Modeling of 6T SRAM Backend Structure Using Sentaurus Interconnect",
		creator: "qinz",
		owner: "karthikg",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "10/22/10",
		pdf: "greadme.pdf"
	},
	{
		name: "SRAM_Backend_Rounding",
		title: "Processing and Modeling of 6T SRAM Back-end Structure Using Sentaurus Interconnect",
		creator: "qinz",
		owner: "karthikg",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "E-2010.09 10/22/10",
		pdf: "greadme.pdf"
	},
	{
		name: "SolderBump_Reliability",
		title: "Mechanical Reliability Analysis of Advanced Bumping Schemes Under Chip-Package Interaction",
		creator: "ramakant",
		owner: "adityap",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Rely",
		dim: "3d",
		tools: "sintercon",
		keywords: "reliability analysis for three bumping schemes under typical chip-package interaction",
		solvNetId: "applib",
		firstRelease: "I-2013.12 08/27/14",
		pdf: "greadme.pdf"
	},
	{
		name: "TSV/TSV_Crack",
		title: "Performance and Reliability Analysis of Through-Silicon Via Structures Using Sentaurus Interconnect",
		creator: "adityap",
		owner: "adityap",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "E-2010.12 12/14/10",
		pdf: "greadme.pdf"
	},
	{
		name: "TSV/TSV_Mobility",
		title: "Performance and Reliability Analysis of Through-Silicon Via Structures Using Sentaurus Interconnect",
		creator: "adityap",
		owner: "adityap",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "E-2010.12 12/14/10",
		pdf: "greadme.pdf"
	},
	{
		name: "TSV_Microbump",
		title: "Analysis of Microbump Impact on Performance and Reliability in 3D Chip Stacks Using Sentaurus Interconnect",
		creator: "cnl",
		owner: "adityap",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "E-2010.12 07/01/11",
		pdf: "greadme.pdf"
	},
	{
		name: "ViscoCalibration",
		title: "Calibration of Silicon Dioxide Viscoelasticity Using Sentaurus Interconnect",
		creator: "adityap",
		owner: "adityap",
		archive: "Applications_Library/Backend",
		appArea: "Backend-Stress",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "M-2016.12 03/23/17",
		pdf: "greadme.pdf"
	},
	{
		name: "HBT_SiGe/HBT_BV",
		title: "Sentaurus Technology Template: Characterization of Bipolar Transistors",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Bipolar",
		appArea: "Bipolar",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "HBT_SiGe/HBT_DC",
		title: "Sentaurus Technology Template: Characterization of Bipolar Transistors",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Bipolar",
		appArea: "Bipolar",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "HBT_SiGe/HBT_Noise",
		title: "Sentaurus Technology Template: Characterization of Bipolar Transistors",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Bipolar",
		appArea: "Bipolar",
		dim: "2d",
		tools: "sde sdevice svisual",
		solvNetId: "applib",
		firstRelease: "L-2016.03",
		pdf: "greadme.pdf"
	},
	{
		name: "HBT_SiGe/HBT_RF",
		title: "Sentaurus Technology Template: Characterization of Bipolar Transistors",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Bipolar",
		appArea: "Bipolar",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "HBT_SiGe_Processing",
		title: "Sentaurus Technology Template: SiGe HBT Processing",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Bipolar",
		appArea: "Bipolar",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_0.35um",
		title: "Sentaurus Technology Template: 0.35 &micro;m Generic CMOS Flow and Characterization",
		creator: "cilento",
		owner: "strauss",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Legacy",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "E-2010.12 08/22/11",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_130nm",
		title: "Process and Device Simulation of 130 nm Generation CMOS Device Featuring 60 nm Transistors Operating at 1.4 V",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Legacy",
		dim: "2d",
		tools: "sprocess sdevice svisual",
		solvNetId: "applib",
		firstRelease: "M-2016.12",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_180nm",
		title: "Process and Device Simulation of 180 nm Generation CMOS Device Featuring LOCOS and Shallow Trench Isolation",
		creator: "sayed",
		owner: "arupsaha",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Legacy",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "L-2016.03",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_45nm_NarrowWidth",
		title: "Exploring Narrow Width Effect on 45-nm CMOS Device Performance Using 3D TCAD Simulations",
		creator: "simeonov",
		owner: "arupsaha",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "A-2008.09 06/01/09",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_Characterization",
		title: "Sentaurus Technology Template: CMOS Characterization",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_Noise",
		title: "Noise Characterization of 32 nm CMOS",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "L-2016.03 01/22/16",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_Processing",
		title: "Sentaurus Technology Template: CMOS Processing",
		creator: "sayed",
		owner: "arupsaha",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "CMOS_RF",
		title: "RF Characterization of 32 nm CMOS",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "J-2014.09 09/05/14",
		pdf: "greadme.pdf"
	},
	{
		name: "FDSOI",
		title: "Process and Device Simulation of Ultrathin Body and Box FDSOI MOSFET",
		creator: "arupsaha",
		owner: "arupsaha",
		appArea: "CMOS-Logic",
		archive: "Applications_Library/CMOS",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "J-2014.09 01/21/15",
		pdf: "greadme.pdf"
	},
	{
		name: "IMOS",
		title: "Simulation of an N-Channel Impact Ionization MOS Transistor",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "C-2009.06 07/16/09",
		pdf: "greadme.pdf"
	},
	{
		name: "NMOS_KMC",
		title: "Sentaurus Technology Template: Hybrid Continuum and Atomistic Simulations in Sentaurus Process",
		creator: "qinz",
		owner: "sameers",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sprocess kmc sdevice",
		solvNetId: "applib",
		firstRelease: "A-2007.12",
		pdf: "greadme.pdf"
	},
	{
		name: "NMOS_SSE",
		title: "Sentaurus Technology Template: Simulation of 3D NMOS Transistor",
		creator: "simeonov",
		owner: "sameers",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "3d",
		tools: "sde-procem sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06",
		pdf: "greadme.pdf"
	},
	{
		name: "PDSOI",
		title: "Process and Device Simulation of Partially Depleted SOI MOSFET",
		creator: "simeonov",
		owner: "arupsaha",
		archive: "Applications_Library/CMOS",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "A-2007.12",
		pdf: "greadme.pdf"
	},
	{
		name: "FinFET_10nm",
		title: "Three-dimensional Device Simulations of 10 nm FinFETs Using Monte Carlo Model and Drift-Diffusion Model With Ballistic Mobility",
		creator: "munkangc",
		owner: "munkangc",
		archive: "Applications_Library/FinFET",
		appArea: "FinFET",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 11/22/13",
		pdf: "greadme.pdf"
	},
	{
		name: "FinFET_14nm",
		title: "Three-dimensional Simulation of 14/16 nm FinFETs with Round Fin Corners and Tapered Fin Shape",
		creator: "munkangc",
		owner: "munkangc",
		archive: "Applications_Library/FinFET",
		appArea: "FinFET",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 06/20/13",
		pdf: "greadme.pdf"
	},
	{
		name: "FinFET_22nm",
		title: "Three-dimensional Simulations of Raised Source-Drain FinFET",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/FinFET",
		appArea: "FinFET",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06",
		pdf: "greadme.pdf"
	},
	{
		name: "TriGateNMOS_InGaAs",
		title: "Simulation of InGaAs-based Planar and Tri-gated NMOSFET Devices",
		creator: "qinz",
		owner: "qinz",
		archive: "Applications_Library/FinFET",
		appArea: "FinFET",
		dim: "2d/3d",
		tools: "sprocess",
		solvNetId: "applib",
		firstRelease: "01/20/14",
		pdf: "greadme.pdf"
	},
	{
		name: "HEMT_InGaAs/HEMT_BV",
		title: "Sentaurus Technology Template: DC and RF Characterization of HEMTs",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Hetero",
		appArea: "Hetero-RF-IIIV",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "10/04/06",
		pdf: "greadme.pdf"
	},
	{
		name: "HEMT_InGaAs/HEMT_DC",
		title: "Sentaurus Technology Template: DC and RF Characterization of HEMTs",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Hetero",
		appArea: "Hetero-RF-IIIV",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "10/04/06",
		pdf: "greadme.pdf"
	},
	{
		name: "HEMT_InGaAs/HEMT_RF",
		title: "Sentaurus Technology Template: DC and RF Characterization of HEMTs",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Hetero",
		appArea: "Hetero-RF-IIIV",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "10/04/06",
		pdf: "greadme.pdf"
	},
	{
		name: "HFET_GaN_DC",
		title: "Sentaurus Technology Template: Simulation of DC Characteristics of a GaN-based HFET",
		creator: "ilyar",
		owner: "ilyar",
		archive: "Applications_Library/Hetero",
		appArea: "Hetero-GaN",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "11/01/13",
		pdf: "greadme.pdf"
	},
	{
		name: "DRAM-Access_VerticalPillar",
		title: "Three-dimensional TCAD Simulation of 3D Vertical Pillar NFET",
		creator: "simeonov",
		owner: "simeonov",
		archive: "Applications_Library/Memory",
		appArea: "Memory-DRAM",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 06/28/12",
		pdf: "greadme.pdf"
	},
	{
name: "FeFET_CAM/FeFET_CAM_array",
title: "Simulation of Ferroelectric FET based Content Addressable Memory",
creator: "mavilla",
owner: "mavilla",
appArea: "Memory",
archive: "Applications_Library/Memory",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "T-2022.03 12/16/2021",
pdf: "greadme.pdf"
	},
	{
name: "FeFET_CAM/FeFET_CAM_cell",
title: "Simulation of Ferroelectric FET based Content Addressable Memory",
creator: "mavilla",
owner: "mavilla",
appArea: "Memory",
archive: "Applications_Library/Memory",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "T-2022.03 12/16/2021",
pdf: "greadme.pdf"
	},
	{
		name: "NAND_GrainField",
		title: "Impact of Polysilicon Grain Boundary Trap on Macaroni-Body NAND Device Simulation",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/Memory",
		appArea: "Memory-NV",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "U-2022.12",
		pdf: "greadme.pdf"
	},
	{
		name: "NAND_SPX_SDevice_32L",
		title: "Sentaurus Process Explorer to Sentaurus Device Link for 3D NAND Simulations",
		creator: "xiwei",
		owner: "xiwei",
		archive: "Applications_Library/Memory",
		appArea: "Memory-NV",
		dim: "3d",
		tools: "spx sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "U-2022.12",
		pdf: "greadme.pdf"
	},
	{
		name: "NAND_VerticalGate_PolyGrain/NAND_PolyGrain_Dist",
		title: "Effects of Grain Boundary Traps on V<sub>th</sub> Variation in 3D NAND Flash Memory Cells",
		creator: "xiwei",
		owner: "xiwei",
		archive: "Applications_Library/Memory",
		appArea: "Memory-NV",
		dim: "3d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.03 01/17/13",
		pdf: "greadme.pdf"
	},
	{
		name: "NAND_VerticalGate_PolyGrain/NAND_PolyGrain_IFM",
		title: "Effects of Grain Boundary Traps on V<sub>th</sub> Variation in 3D NAND Flash Memory Cells",
		creator: "xiwei",
		owner: "xiwei",
		archive: "Applications_Library/Memory",
		appArea: "Memory-NV",
		dim: "3d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.03 01/17/13",
		pdf: "greadme.pdf"
	},
	{
		name: "SF_DRAM",
		title: "Process and Device Simulation of a DRAM Cell with Saddle-Fin Access Transistor and Circuit Elements",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/Memory",
		appArea: "Memory-DRAM",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "N-2017.09",
		pdf: "greadme.pdf"
	},
	{
		name: "SONOS_Memory",
		title: "Sentaurus Technology Template: SONOS Read/Write Operation",
		creator: "sjaboud",
		owner: "sameers",
		archive: "Applications_Library/Memory",
		appArea: "Memory-NV",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "10/23/06",
		pdf: "greadme.pdf"
	},
	{
		name: "SRAM_FinFET_25nm",
		title: "Three-dimensional Simulation of 25-nm FinFET SRAM Cell",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/Memory",
		appArea: "Memory-SRAM-FinFET",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "F-2011.09 12/14/11",
		pdf: "greadme.pdf"
	},
	{
		name: "STT_MTJ",
		title: "Simulation of Magnetization Switching in a CoFeB/MgO/CoFeB Magnetic Tunnel Junction",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Memory",
		appArea: "Memory-Spintronics",
		dim: "2d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "N-2017.09",
		pdf: "greadme.pdf"
	},
	{
		name: "CIS_BSI_4pix",
		title: "Simulation of 3D Backside Illuminated CMOS Image Sensor",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Opto",
		appArea: "Image Sensors",
		dim: "3d",
		tools: "sprocess emw sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 06/11/12",
		pdf: "greadme.pdf"
	},
	{
		name: "CIS_FSI",
		title: "Simulation of 3D Front-Side Illuminated Single-Pixel CMOS Image Sensor",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Opto",
		appArea: "Image Sensors",
		dim: "3d",
		tools: "sprocess emw sdevice",
		solvNetId: "applib",
		firstRelease: "A-2007.12 02/05/08",
		pdf: "greadme.pdf"
	},
	{
		name: "PhotoDetector_Raytracer/PhotoDetector_EQE",
		title: "Sentaurus Technology Template: Simulation of 2D n+-on-p HgCdTe Photodiode with Raytracer",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Opto",
		appArea: "PhotoDetector",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06",
		pdf: "greadme.pdf"
	},
	{
		name: "PhotoDetector_Raytracer/PhotoDetector_IV",
		title: "Sentaurus Technology Template: Simulation of 2D n+-on-p HgCdTe Photodiode with Raytracer",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Opto",
		appArea: "PhotoDetector",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06",
		pdf: "greadme.pdf"
	},
	{
		name: "BoostConverter_GaN-SiC/BoostConverter_MixedMode",
		title: "Optimization of GaN MISFET and DC Boost Converter Circuit",
		creator: "ilyar",
		owner: "ilyar",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "I-2013.12 03/14/14",
		pdf: "greadme.pdf"
	},
	{
		name: "BoostConverter_GaN-SiC/MISFET_BV",
		title: "Optimization of GaN MISFET and DC Boost Converter Circuit",
		creator: "ilyar",
		owner: "ilyar",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "I-2013.12 03/14/14",
		pdf: "greadme.pdf"
	},
	{
		name: "FB-Inverter_RC-IGBT/FB_Inverter",
		title: "Simulation of Reverse-Conducting IGBT Device and Full-Bridge Inverter Using TCAD Sentaurus",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "L-2016.03 04/14/16",
		pdf: "greadme.pdf"
	},
	{
		name: "FB-Inverter_RC-IGBT/RC-IGBT",
		title: "Simulation of Reverse-Conducting IGBT Device and Full-Bridge Inverter Using TCAD Sentaurus",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "L-2016.03 04/14/16",
		pdf: "greadme.pdf"
	},
	{
name: "Ga2O3_MOSCAP_MOSFET",
title: "Simulation of Gallium Oxide MOS Devices With TCAD Sentaurus",
creator: "vinayd",
owner: "vinayd",
archive: "Applications_Library/Power",
appArea: "Power-Ga2O3",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09",
pdf: "greadme.pdf"
	},
	{
name: "GaN/GaN_AlGaN_Polarization",
title: "Simulation of Polarization-Induced Effects at AlGaN-GaN Heterointerfaces",
creator: "vinayd",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sprocess sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/20",
pdf: "greadme.pdf"
	},
	{
name: "GaN/GaN_AlGaN_Polz_Calculated",
title: "Simulation of Normally On GaN HEMT Device by Using Calculated Polarization Charges",
creator: "vinayd",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sprocess sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/GaN_Fin-HEMT",
title: "Three-Dimensional Simulation of GaN Fin-HEMT",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "3d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/GaN_HEMT_FermiStat",
title: "Using Carrier Statistics to Model 2D Electron Gas at AlGaN-GaN Interface",
creator: "vinayd",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sprocess sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/GaN_HFET_SH",
title: "Modeling of Self-Heating Effects in GaN HFETs",
creator: "gzandler",
owner: "mavilla",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
		name: "GaN/GaN_Processing",
		title: "Process and Device Simulations of GaN HFET Devices",
		creator: "qinz",
		owner: "qinz",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "2d",
		tools: "sprocess sdevice",
		keywords: "GaN",
		solvNetId: "applib",
		firstRelease: "J-2014.09 10/15/14",
		pdf: "greadme.pdf"
	},
	{
name: "GaN/GaN_Vertical_MOSFET_SW",
title: "Simulation of Vertical GaN Devices: Trench-Gate MOSFET and Diodes",
creator: "keunsam",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
		name: "GaN/HFET_pGate_GaN",
		title: "Simulation of Normally Off AlGaN/GaN HFET with P-Type GaN Gate and AlGaN Buffer",
		creator: "hywong",
		owner: "hywong",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "E-2010.12 05/24/11",
		pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_Barrier_TAT_1D",
title: "Simulation of Leakage Through AlGaN Barriers in Typical p-GaN Gate HEMT Layer Structures",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "1d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_HEMT",
title: "Two-Dimensional Device Simulation of p-GaN Gate HEMTs",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_HEMT_CC",
title: "Modeling and Simulation of Trapping Effects in p-GaN Gate HEMT Gate Injection Transistor",
creator: "gzandler",
owner: "mavilla",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sprocess sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_HEMT_VtInstability",
title: "Threshold Voltage Instability in p-GaN Gate HEMTs Under Gate Voltage Stress",
creator: "mavilla",
owner: "mavilla",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "S-2021.06 06/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_Leakage",
title: "Two-Dimensional Simulation of Leakage in Source-Side Stack of p-GaN Gate HEMTs",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_Schottky_1D",
title: "Simulation of Leakage due to Tunneling in p-GaN Schottky Barriers",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "1d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_Schottky_2D",
title: "Two-Dimensional Simulation of Corner-Rounding Effects in p-GaN Schottky Barriers",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "2d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pGate_Schottky_TAT_1D",
title: "Simulation of Leakage due to Trap-Assisted Tunneling in p-GaN Schottky Barriers",
creator: "nbraga",
owner: "vinayd",
appArea: "GaN",
archive: "Applications_Library/Power",
dim: "1d",
tools: "sde sdevice",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/2020",
pdf: "greadme.pdf"
	},
	{
name: "GaN/pHEMT_Flyback",
title: "p-GaN Gate HEMT-Based Flyback DC/DC Converter",
creator: "vinayd",
owner: "vinayd",
archive: "Applications_Library/Power",
appArea: "GaN",
dim: "2d",
tools: "sde sdevice",
keywords: "GaN pHEMT Mixed-mode Flyback",
solvNetId: "applib",
firstRelease: "S-2021.06 06/01/2020",
pdf: "greadme.pdf"
	},
	{
		name: "IGBT",
		title: "Sentaurus Technology Template: IGBT Characterization",
		creator: "sayed",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sde noffset sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "IGBT_MeltLaserAnneal",
		title: "IGBT Characterization With Backside Melt Laser Annealing",
		creator: "csyun",
		owner: "csyun",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 06/20/13",
		pdf: "greadme.pdf"
	},
	{
		name: "IGBT_TrenchFieldStop",
		title: "Three-dimensional Process and Device Simulations of Trench-Gate IGBT Power Device Using TCAD Sentaurus",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "3d",
		tools: "sprocess sdevice",
		keywords: "Trench-gate Field-stop IGBT 3D Process and Device Simulation",
		solvNetId: "applib",
		firstRelease: "J-2014.09 12/08/14",
		pdf: "greadme.pdf"
	},
	{
		name: "LDMOS_Degradation",
		title: "Hot-Carrier Stress Degradation Simulation of LDMOS Device Using TCAD Sentaurus",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "J-2014.09 03/12/15",
		pdf: "greadme.pdf"
	},
	{
		name: "LDMOS_Processing",
		title: "Sentaurus Technology Template: LDMOS Processing",
		creator: "qinz",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "06/20/06",
		lastRelease: "U-2022.12",
		pdf: "greadme.pdf"
	},
	{
		name: "MOSFET_SuperJunction",
		title: "TCAD Sentaurus Simulation of 3D Superjunction Vertically Double-Diffused MOSFET",
		creator: "arupsaha",
		owner: "arupsaha",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "3d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "O-2018.06",
		pdf: "greadme.pdf"
	},
	{
name: "SiC/DT_NMOS_SiC-4H",
title: "Process and Device Simulation of 4H-SiC Double Trench NMOS Device Using TCAD Sentaurus",
tag: "new",
creator: "vinayd",
owner: "vinayd",
archive: "Applications_Library/Power",
appArea: "Power-GaN-SiC",
dim: "2d",
tools: "sprocess",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/20",
lastUpdate: "09/01/20",
pdf: "greadme.pdf"
	},
	{
name: "SiC/NMOS_SiC-4H",
title: "Process and Device Simulation of 4H-SiC NMOS Device Using TCAD Sentaurus",
tag: "new",
creator: "vinayd",
owner: "vinayd",
archive: "Applications_Library/Power",
appArea: "Power-GaN-SiC",
dim: "2d",
tools: "sprocess",
solvNetId: "applib",
firstRelease: "K-2015.06 08/20/15",
lastUpdate: "08/20/15",
pdf: "greadme.pdf"
	},
	{
name: "SiC/SJ_UMOS_SiC-4H",
title: "Process and Device Simulation of 4H-SiC Superjunction UMOS Device Using TCAD Sentaurus",
tag: "new",
creator: "vinayd",
owner: "vinayd",
archive: "Applications_Library/Power",
appArea: "Power-GaN-SiC",
dim: "2d",
tools: "sprocess",
solvNetId: "applib",
firstRelease: "R-2020.09 09/01/20",
lastUpdate: "09/01/20",
pdf: "greadme.pdf"
	},
	{
		name: "SiC/SchottkyDiode_SiC",
		title: "Sentaurus Technology Template: 4H-SiC Schottky Diode",
		creator: "skrisha",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "Y-2006.06",
		pdf: "greadme.pdf"
	},
	{
name: "SiC/Schottky_Process_4H-SiC",
title: "Process and Device Simulation of 4H-SiC Schottky Diodes Using TCAD Sentaurus",
creator: "vinayd",
owner: "vinayd",
archive: "Applications_Library/Power",
appArea: "Power-GaN-SiC",
dim: "2d",
tools: "sprocess sdevice",
solvNetId: "applib",
firstRelease: "M-2016.12 04/05/17",
pdf: "greadme.pdf"
	},
	{
		name: "SiC/nIGBT_SiC-4H",
		title: "Device Simulation of 3D Trench Gate 4H-SiC IGBT Device",
		creator: "nitesh",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 11/27/13",
		pdf: "greadme.pdf"
	},
	{
		name: "SiC/pIGBT_SiC-4H",
		title: "Simulation of 4H-SiC pIGBT With TCAD Sentaurus",
		creator: "pavelt",
		owner: "pavelt",
		archive: "Applications_Library/Power",
		appArea: "Power-GaN-SiC",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "I-2013.12 02/28/14",
		pdf: "greadme.pdf"
	},
	{
		name: "Si_SJ-IGBT",
		title: "Three-dimensional Process and Device Simulation of Superjunction IGBT Device",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "3d",
		tools: "sprocess sdevice",
		keywords: "Superjunction IGBT 3D Process and Device Simulation",
		solvNetId: "applib",
		firstRelease: "L-2016.03 03/01/16",
		pdf: "greadme.pdf"
	},
	{
		name: "Thyristor",
		title: "Sentaurus Technology Template: Light Triggered Thyristor",
		creator: "sayed",
		owner: "sameers",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.pdf"
	},
	{
		name: "TrenchGateIGBT_2d",
		title: "Two-dimensional Process and Device Simulation of Trench-Gate Field-Stop IGBT Power Device",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sprocess sdevice",
		keywords: "N-Injector Trench-gate Field-stop IGBT 2D Process and Device Simulation",
		solvNetId: "applib",
		firstRelease: "I-2013.12 08/27/14",
		pdf: "greadme.pdf"
	},
	{
		name: "TrenchGateNMOS",
		title: "Three-dimensional Process and Device Simulations of Trench-Gate NMOS Power Device Using TCAD Sentaurus",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "3d",
		tools: "sprocess sdevice",
		keywords: "Trench-Gate NMOS Power",
		solvNetId: "applib",
		firstRelease: "J-2014.09 10/14/14",
		pdf: "greadme.pdf"
	},
	{
		name: "TrenchGateNMOS_2d",
		title: "Two-dimensional Process and Device Simulation of Trench-Gate NMOS Power  Device Using TCAD Sentaurus",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sprocess sdevice",
		keywords: "Trench-Gate NMOS Schottky barrier diode BV UIS",
		solvNetId: "applib",
		firstRelease: "I-2013.12 06/30/14",
		pdf: "greadme.pdf"
	},
	{
		name: "UnclampedInductiveSwitch",
		title: "Modeling the Unclamped Inductive Switching Capabilities of Silicon Power Devices Using TCAD Sentaurus",
		creator: "csyun",
		owner: "arupsaha",
		archive: "Applications_Library/Power",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 01/30/13",
		pdf: "greadme.pdf"
	},
	{
		name: "HCD_FinFET",
		title: "Hot-Carrier Degradation Based on Reaction Drift-Diffusion",
		creator: "mengd",
		owner: "mengd",
		archive: "Applications_Library/Reliability",
		appArea: "Reliability",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "T-2022.03",
		pdf: "greadme.pdf"
	},
	{
		name: "NBTI_FinFET",
		title: "Negative Bias Temperature Instability Simulation in FinFET Technology",
		creator: "mengd",
		owner: "mengd",
		archive: "Applications_Library/Reliability",
		appArea: "Reliability",
		dim: "3d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "T-2022.03",
		pdf: "greadme.pdf"
	},
	{
		name: "HallSensor",
		title: "Three-dimensional Hall Sensor Simulation with TCAD Sentaurus",
		creator: "pavelt",
		owner: "pavelt",
		archive: "Applications_Library/Sensors",
		appArea: "Sensors",
		dim: "3d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "E-2010.12 01/03/11",
		pdf: "greadme.pdf"
	},
	{
		name: "PressureSensor",
		title: "Pressure Sensor Simulation Using Sentaurus TCAD Suite",
		creator: "vinayd",
		owner: "vinayd",
		archive: "Applications_Library/Sensors",
		appArea: "Sensors",
		dim: "3d",
		tools: "sinterconnect",
		solvNetId: "applib",
		firstRelease: "04/19/13",
		pdf: "greadme.pdf"
	},
	{
		name: "DistBraggReflector",
		title: "Simulation of N-Type AlGaAs DBR Layer Stack for III-V Compound Solar Cells",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d",
		tools: "sde matpar sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 10/18/12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_DualJunct_GaAs",
		title: "Simulation of a GaAs/GaInP Dual-Junction Solar Cell",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d",
		solvNetId: "applib",
		tools: "sde matpar sdevice",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_SingleJunct_GaAs/SolarCell_EQE",
		title: "Simulation of 2D Single-Junction GaAs Solar Cell",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d",
		tools: "sde matpar sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 09/12/12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_SingleJunct_GaAs/SolarCell_IV",
		title: "Simulation of 2D Single-Junction GaAs Solar Cell",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d",
		tools: "sde matpar sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 09/12/12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_BackCont",
		title: "Three-dimensional All-Back-Contact Monocrystalline Silicon Solar-Cell Simulation",
		creator: "joanneh",
		owner: "joanneh",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "3d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "G-2012.06 07/06/12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_BackContOpt",
		title: "Optimization of Rear Contact Design in Monocrystalline Silicon Solar-Cell Using 3D TCAD Simulations",
		creator: "joanneh",
		owner: "joanneh",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "3d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "D-2010.03 07/16/10",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_RandTexture",
		title: "Three-dimensional Optical Simulation of Textured Surface Silicon Solar Cell",
		creator: "joanneh",
		owner: "joanneh",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "3d",
		tools: "sde sdevice",
		solvNetId: "applib",
		firstRelease: "F-2011.09 01/12/12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_Texture/SolarCell_Texture_EQE",
		title: "Sentaurus Technology Template: EQE and I-V Curve Calculation of a Textured Silicon Solar Cell",
		creator: "letay",
		owner: "letay",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d/3d",
		tools: "sde sdevice inspect",
		solvNetId: "applib",
		firstRelease: "E-2010.12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_Texture/SolarCell_Texture_IV",
		title: "Sentaurus Technology Template: EQE and I-V Curve Calculation of a Textured Silicon Solar Cell",
		creator: "letay",
		owner: "letay",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d/3d",
		tools: "sde sdevice inspect",
		solvNetId: "applib",
		firstRelease: "E-2010.12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_Texture/SolarCell_Texture_OPTO_2d",
		title: "Sentaurus Technology Template: EQE and I-V Curve Calculation of a Textured Silicon Solar Cell",
		creator: "letay",
		owner: "letay",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d/3d",
		tools: "sde sdevice inspect",
		solvNetId: "applib",
		firstRelease: "E-2010.12",
		pdf: "greadme.pdf"
	},
	{
		name: "SolarCell_cSi_Texture/SolarCell_Texture_OPTO_3d",
		title: "Sentaurus Technology Template: EQE and I-V Curve Calculation of a Textured Silicon Solar Cell",
		creator: "letay",
		owner: "letay",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d/3d",
		tools: "sde sdevice inspect",
		solvNetId: "applib",
		firstRelease: "E-2010.12",
		pdf: "greadme.pdf"
	},
	{
		name: "TunnelDiode_Basic_IV",
		title: "Simulation of a Simple GaAs Tunnel Diode for Multijunction Solar Cells",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d",
		tools: "sde matpar sdevice",
		solvNetId: "applib",
		firstRelease: "F-2011.09 10/19/11",
		pdf: "greadme.pdf"
	},
	{
		name: "TunnelDiode_IV",
		title: "Simulation of a Realistic GaAs Tunnel Diode for Multijunction Solar Cells",
		creator: "sameers",
		owner: "sameers",
		archive: "Applications_Library/Solar",
		appArea: "Solar",
		dim: "2d",
		tools: "sde matpar sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 05/01/13",
		pdf: "greadme.pdf"
	},
	{
		name: "HBT_SiGe",
		title: "Sentaurus Technology Template: SiGe HBT",
		creator: "sayed",
		owner: "sayed",
		archive: "Applications_Library/Templates",
		appArea: "Bipolar",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "X-2005.10",
		pdf: "greadme.html"
	},
	{
		name: "LDMOS",
		title: "Sentaurus Technology Template: LDMOS",
		creator: "qinz",
		owner: "sayed",
		archive: "Applications_Library/Templates",
		appArea: "Power-Si-Discrete",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "06/20/06",
		pdf: "greadme.html"
	},
	{
		name: "NMOS",
		title: "Sentaurus Technology Template: NMOS",
		creator: "sayed",
		owner: "sayed",
		archive: "Applications_Library/Templates",
		appArea: "CMOS-Logic",
		dim: "2d",
		tools: "sprocess sdevice",
		solvNetId: "applib",
		firstRelease: "J-2014.09",
		pdf: "greadme.html"
	},
	{
		name: "FDSOI_Variability_sIFM",
		title: "Modeling Statistical Variability in FDSOI MOSFETs Using the Statistical Impedance Field Method",
		creator: "sjaboud",
		owner: "sjaboud",
		archive: "Applications_Library/Variability",
		appArea: "Variability-Stat",
		dim: "2d",
		tools: "sdevice svisual",
		solvNetId: "applib",
		firstRelease: "K-2015.06 06/05/15",
		pdf: "greadme.pdf"
	},
	{
		name: "FinFET_Variability_sIFM",
		title: "Modeling Random Variability Effects With the Statistical Impedance Field Method",
		creator: "sayed",
		owner: "sjaboud",
		archive: "Applications_Library/Variability",
		appArea: "Variability-Stat",
		dim: "3d",
		tools: "sdevice svisual",
		solvNetId: "applib",
		firstRelease: "G-2012.06 02/01/13",
		pdf: "greadme.pdf"
	},
	{
		name: "SRAM_Variability/SRAM_3d",
		title: "Modeling Statistical Variability of Static Noise Margins of SRAM Cells Using the Statistical Impedance Field Method",
		creator: "sayed",
		owner: "sjaboud",
		archive: "Applications_Library/Variability",
		appArea: "Variability-Stat",
		dim: "3d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 05/10/13",
		pdf: "greadme.pdf"
	},
	{
		name: "SRAM_Variability/SRAM_MixedMode",
		title: "Modeling Statistical Variability of Static Noise Margins of SRAM Cells Using the Statistical Impedance Field Method",
		creator: "sayed",
		owner: "sjaboud",
		archive: "Applications_Library/Variability",
		appArea: "Variability-Stat",
		dim: "3d",
		tools: "sdevice",
		solvNetId: "applib",
		firstRelease: "H-2013.03 05/10/13",
		pdf: "greadme.pdf"
	},
	{
		name: "emw/import-codev",
		title: "emw/import-codev",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/emw",
		tools: "emw",
		pdf: "greadme.html"
	},
	{
		name: "emw/simple-cis",
		title: "emw/simple-cis",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/emw",
		tools: "emw",
		pdf: "greadme.html"
	},
	{
		name: "emw/simple2d-postprocess",
		title: "emw/simple2d-postprocess",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/emw",
		tools: "emw",
		pdf: "greadme.html"
	},
	{
		name: "emw/simple2d-sdevice",
		title: "emw/simple2d-sdevice",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/emw",
		tools: "emw",
		pdf: "greadme.html"
	},
	{
		name: "emw/simple2d",
		title: "emw/simple2d",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/emw",
		tools: "emw",
		pdf: "greadme.html"
	},
	{
		name: "emw/simple3d",
		title: "emw/simple3d",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/emw",
		tools: "emw",
		pdf: "greadme.html"
	},
	{
		name: "python/band_dgm",
		title: "python/band_dgm",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/python",
		tools: "svisualpy",
		pdf: "greadme.html"
	},
	{
		name: "python/bv_extract",
		title: "python/bv_extract",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/python",
		tools: "svisualpy",
		pdf: "greadme.html"
	},
	{
		name: "python/py_basics",
		title: "python/py_basics",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/python",
		tools: "gpythonsh",
		pdf: "greadme.html"
	},
	{
		name: "sde/BJT",
		title: "sde/BJT",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/ExternalProfiles",
		title: "sde/ExternalProfiles",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/FinFET",
		title: "sde/FinFET",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/FinFET_procem",
		title: "sde/FinFET_procem",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/MOSFET3d",
		title: "sde/MOSFET3d",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/SimpleDiode",
		title: "sde/SimpleDiode",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/sigehbt",
		title: "sde/sigehbt",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sde/soifet",
		title: "sde/soifet",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sde",
		tools: "sde",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/3Ddiode_demo",
		title: "sdevice/3Ddiode_demo",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/4H-SiC_PiN",
		title: "sdevice/4H-SiC_PiN",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/AC",
		title: "sdevice/AC",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/BJTcurrentBC",
		title: "sdevice/BJTcurrentBC",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/BVmethods",
		title: "sdevice/BVmethods",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/CMOSInverter",
		title: "sdevice/CMOSInverter",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Ferroelectric/Hysteresis",
		title: "sdevice/Ferroelectric/Hysteresis",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/GaN_MOSCAP_1D",
		title: "sdevice/GaN_MOSCAP_1D",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/GaN_PiN_Diode",
		title: "sdevice/GaN_PiN_Diode",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/HBT_Gummel",
		title: "sdevice/HBT_Gummel",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/HarmonicBalance_pn",
		title: "sdevice/HarmonicBalance_pn",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/MCpFinFET",
		title: "sdevice/MCpFinFET",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/MixedMode",
		title: "sdevice/MixedMode",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/MixedModeContactResistance",
		title: "sdevice/MixedModeContactResistance",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/MultiValleyMOS",
		title: "sdevice/MultiValleyMOS",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/SOI_IdVg",
		title: "sdevice/SOI_IdVg",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/SingleDevice",
		title: "sdevice/SingleDevice",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/TransportModels",
		title: "sdevice/TransportModels",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Traps/FillControls",
		title: "sdevice/Traps/FillControls",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Traps/Trap2Doping",
		title: "sdevice/Traps/Trap2Doping",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Traps/TrapDOS",
		title: "sdevice/Traps/TrapDOS",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Traps/TrapOccupation",
		title: "sdevice/Traps/TrapOccupation",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Traps/TrapRecombination",
		title: "sdevice/Traps/TrapRecombination",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/Traps/TrapSpatial",
		title: "sdevice/Traps/TrapSpatial",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/inverter_compact_model",
		title: "sdevice/inverter_compact_model",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/opto/OpticalAC",
		title: "sdevice/opto/OpticalAC",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/opto/rt-angular-r",
		title: "sdevice/opto/rt-angular-r",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/opto/rt-jsc-3d",
		title: "sdevice/opto/rt-jsc-3d",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/opto/tmm-light-iv",
		title: "sdevice/opto/tmm-light-iv",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/opto/tmm-spectral-reflection",
		title: "sdevice/opto/tmm-spectral-reflection",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pGate_HFET",
		title: "sdevice/pGate_HFET",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/cmi_dynamic",
		title: "sdevice/pmi/cmi_dynamic",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/cmi_tres",
		title: "sdevice/pmi/cmi_tres",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/crimi_k_si_rss",
		title: "sdevice/pmi/crimi_k_si_rss",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/crimi_nk_hgcdte_hougen",
		title: "sdevice/pmi/crimi_nk_hgcdte_hougen",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_affinity",
		title: "sdevice/pmi/pmi_affinity",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_avalanche",
		title: "sdevice/pmi/pmi_avalanche",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_bg",
		title: "sdevice/pmi/pmi_bg",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_bgn",
		title: "sdevice/pmi/pmi_bgn",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_currentplot",
		title: "sdevice/pmi/pmi_currentplot",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_effmass",
		title: "sdevice/pmi/pmi_effmass",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_erelaxtime",
		title: "sdevice/pmi/pmi_erelaxtime",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_heatcapacity",
		title: "sdevice/pmi/pmi_heatcapacity",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_hotcarrierinj",
		title: "sdevice/pmi/pmi_hotcarrierinj",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_incomplete",
		title: "sdevice/pmi/pmi_incomplete",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_lifetime",
		title: "sdevice/pmi/pmi_lifetime",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_mobility",
		title: "sdevice/pmi/pmi_mobility",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_mobilitystressfactor",
		title: "sdevice/pmi/pmi_mobilitystressfactor",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_msc_abes",
		title: "sdevice/pmi/pmi_msc_abes",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_msc_currentplot",
		title: "sdevice/pmi/pmi_msc_currentplot",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_newtonstep",
		title: "sdevice/pmi/pmi_newtonstep",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_nonlocal_recomb",
		title: "sdevice/pmi/pmi_nonlocal_recomb",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_polarization",
		title: "sdevice/pmi/pmi_polarization",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_quantumyield",
		title: "sdevice/pmi/pmi_quantumyield",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_recomb",
		title: "sdevice/pmi/pmi_recomb",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_spacefactor",
		title: "sdevice/pmi/pmi_spacefactor",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_stress",
		title: "sdevice/pmi/pmi_stress",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_thermalcond",
		title: "sdevice/pmi/pmi_thermalcond",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/pmi_thinlayer_kappa",
		title: "sdevice/pmi/pmi_thinlayer_kappa",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/pmi/tcl_currentplot",
		title: "sdevice/pmi/tcl_currentplot",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sdevice/ring_oscillator",
		title: "sdevice/ring_oscillator",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sdevice",
		tools: "sdevice",
		pdf: "greadme.html"
	},
	{
		name: "sinterconnect/3D_Cantilever",
		title: "sinterconnect/3D_Cantilever",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sinterconnect",
		tools: "sinterconnect",
		pdf: "greadme.html"
	},
	{
		name: "sinterconnect/3D_Interconnect",
		title: "sinterconnect/3D_Interconnect",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sinterconnect",
		tools: "sinterconnect",
		pdf: "greadme.html"
	},
	{
		name: "sinterconnect/3D_Matrix_Calculation",
		title: "sinterconnect/3D_Matrix_Calculation",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sinterconnect",
		tools: "sinterconnect",
		pdf: "greadme.html"
	},
	{
		name: "sinterconnect/DualDamascene",
		title: "sinterconnect/DualDamascene",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sinterconnect",
		tools: "sinterconnect",
		pdf: "greadme.html"
	},
	{
		name: "sinterconnect/Inverter",
		title: "sinterconnect/Inverter",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sinterconnect",
		tools: "sinterconnect",
		pdf: "greadme.html"
	},
	{
		name: "siwb/siwb_for_process",
		title: "siwb/siwb_for_process",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/siwb",
		tools: "siwb",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/Basics",
		title: "snmesh/Basics",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/Deatomization",
		title: "snmesh/Deatomization",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/DopingNameConventions",
		title: "snmesh/DopingNameConventions",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/EvaluateFunction",
		title: "snmesh/EvaluateFunction",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/MeshQuality",
		title: "snmesh/MeshQuality",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/ProfileConstruction3D",
		title: "snmesh/ProfileConstruction3D",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/ProfileOverlap",
		title: "snmesh/ProfileOverlap",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/Profiles",
		title: "snmesh/Profiles",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/RefineControls",
		title: "snmesh/RefineControls",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/RefineInterface",
		title: "snmesh/RefineInterface",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/Refinements",
		title: "snmesh/Refinements",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/Smoothing",
		title: "snmesh/Smoothing",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/SubMeshes",
		title: "snmesh/SubMeshes",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/TensorDoping",
		title: "snmesh/TensorDoping",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/TensorEMW",
		title: "snmesh/TensorEMW",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/TensorGarand",
		title: "snmesh/TensorGarand",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/TensorMesh",
		title: "snmesh/TensorMesh",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "snmesh/Tools",
		title: "snmesh/Tools",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/snmesh",
		tools: "snmesh",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/1DGS",
		title: "sprocess/1DGS",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/2DGS",
		title: "sprocess/2DGS",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Alagator",
		title: "sprocess/Alagator",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Custom_calibration",
		title: "sprocess/Custom_calibration",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Fourier",
		title: "sprocess/Fourier",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Fourier3D",
		title: "sprocess/Fourier3D",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/GDSreader",
		title: "sprocess/GDSreader",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/KMC",
		title: "sprocess/KMC",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/LKMC_25nmFinFET",
		title: "sprocess/LKMC_25nmFinFET",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/LKMC_Epitaxy_SiP",
		title: "sprocess/LKMC_Epitaxy_SiP",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/LKMC_SPER-2Dfin",
		title: "sprocess/LKMC_SPER-2Dfin",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/LKMC_SPER_snowplough",
		title: "sprocess/LKMC_SPER_snowplough",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Models",
		title: "sprocess/Models",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Remeshing",
		title: "sprocess/Remeshing",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/Remeshing_for_Device",
		title: "sprocess/Remeshing_for_Device",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/SmallMOS_2D3D",
		title: "sprocess/SmallMOS_2D3D",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/SmallMOS_Full",
		title: "sprocess/SmallMOS_Full",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sprocess/SmallMOS_NoDiff",
		title: "sprocess/SmallMOS_NoDiff",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sprocess",
		tools: "sprocess",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/PMC_Ion_Assisted_Etch",
		title: "sptopo3d/PMC_Ion_Assisted_Etch",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/PMC_Ion_Assisted_Etch_Ar_Plasma",
		title: "sptopo3d/PMC_Ion_Assisted_Etch_Ar_Plasma",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/PMC_Metrology",
		title: "sptopo3d/PMC_Metrology",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/PMC_Simple_Deposition",
		title: "sptopo3d/PMC_Simple_Deposition",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/PMC_Simple_Etch",
		title: "sptopo3d/PMC_Simple_Etch",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/RFM_Flux_Models",
		title: "sptopo3d/RFM_Flux_Models",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/RFM_Simple_Iso_Etch",
		title: "sptopo3d/RFM_Simple_Iso_Etch",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/depo_hdp",
		title: "sptopo3d/depo_hdp",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/depo_hdp_sp",
		title: "sptopo3d/depo_hdp_sp",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/etch_rie2",
		title: "sptopo3d/etch_rie2",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "sptopo3d/layout",
		title: "sptopo3d/layout",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/sptopo3d",
		tools: "sptopo3d",
		pdf: "greadme.html"
	},
	{
		name: "svisual/export",
		title: "svisual/export",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisual",
		pdf: "greadme.html"
	},
	{
		name: "svisual/python/extract",
		title: "svisual/python/extract",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisualpy",
		pdf: "greadme.html"
	},
	{
		name: "svisual/python/ifm",
		title: "svisual/python/ifm",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisualpy",
		pdf: "greadme.html"
	},
	{
		name: "svisual/python/rfx",
		title: "svisual/python/rfx",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisualpy",
		pdf: "greadme.html"
	},
	{
		name: "svisual/tcl/extract",
		title: "svisual/tcl/extract",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisual",
		pdf: "greadme.html"
	},
	{
		name: "svisual/tcl/ifm",
		title: "svisual/tcl/ifm",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisual",
		pdf: "greadme.html"
	},
	{
		name: "svisual/tcl/rfx",
		title: "svisual/tcl/rfx",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/svisual",
		tools: "svisual",
		pdf: "greadme.html"
	},
	{
		name: "swb/HSpice_bsim4",
		title: "swb/HSpice_bsim4",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"
	},
	{
		name: "swb/SimpleMOS",
		title: "swb/SimpleMOS",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"
	},
	{
		name: "swb/SimpleMOS_py",
		title: "swb/SimpleMOS_py",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"
	},
	{
		name: "swb/TrenchGateNMOS_Ron_BV",
		title: "swb/TrenchGateNMOS_Ron_BV",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"
	},
	{
		name: "swb/analyt_func_grid",
		title: "swb/analyt_func_grid",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"		
	},
	{
		name: "swb/node_preprocess",
		title: "swb/node_preprocess",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"
	},
	{
		name: "swb/parameters_scenarios",
		title: "swb/parameters_scenarios",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/swb",
		tools: "swb",
		pdf: "greadme.html"
	},
	{
		name: "tcadtospice/garand/GarandApp",
		title: "tcadtospice/garand/GarandApp",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "garand enigma",
		pdf: "greadme.html"
	},
	{
		name: "tcadtospice/garand/GarandAppVar",
		title: "tcadtospice/garand/GarandAppVar",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "garand enigma",
		pdf: "greadme.html"
	},
	{
		name: "tcadtospice/mystic/14nmFinFETSentaurus_PltOnly",
		title: "tcadtospice/mystic/14nmFinFETSentaurus_PltOnly",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "sprocess sdevice",
		pdf: "greadme.pdf"	
	},
	{
		name: "tcadtospice/mystic/Mystic_GUI_tutorial",
		title: "tcadtospice/mystic/Mystic_GUI_tutorial",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "enigma mystic_gui",
		pdf: "greadme.html"
	},
	{
		name: "tcadtospice/mystic/Mystic_tutorial",
		title: "tcadtospice/mystic/Mystic_tutorial",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "enigma mystic",
		pdf: "greadme.html"
	},
	{
		name: "tcadtospice/randomspice/14nmFinFETRespSurf_NoLV",
		title: "tcadtospice/randomspice/14nmFinFETRespSurf_NoLV",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "enigma mystic",
		pdf: "greadme.html"	
	},
	{
		name: "tcadtospice/randomspice/14nmFinFETRespSurf_RS2",
		title: "tcadtospice/randomspice/14nmFinFETRespSurf_RS2",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "enigma randomspice",
		pdf: "greadme.html"	
	},
	{
		name: "tcadtospice/setup/14nmFinFETSentaurus_PltOnly",
		title: "tcadtospice/setup/14nmFinFETSentaurus_PltOnly",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "sprocess sdevice",
		pdf: "greadme.pdf"
	},
	{
		name: "tcadtospice/setup/DB_tutorial",
		title: "tcadtospice/setup/DB_tutorial",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcadtospice",
		tools: "enigma",
		pdf: "greadme.html"
	},
	{
		name: "tcl/bv_extract",
		title: "tcl/bv_extract",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcl",
		tools: "tcl",
		pdf: "greadme.html"
	},
	{
		name: "tcl/tcl_basics",
		title: "tcl/tcl_basics",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcl",
		tools: "tcl",
		pdf: "greadme.html"
	},
	{
		name: "tcl/tox_extract",
		title: "tcl/tox_extract",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tcl",
		tools: "tcl",
		pdf: "greadme.html"
	},
	{
		name: "tdx/modify_field",
		title: "tdx/modify_field",
		archive: "Applications_Library/GettingStarted",
		appArea: "GettingStarted/tdx",
		tools: "tdx",
		pdf: "greadme.html"
	}
];
